src/Entity/Events.php
<?php

namespace App\Entity;

use App\Repository\EventsRepository;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=EventsRepository::class)
 */
class Events
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $Nom;

    /**
     * @ORM\Column(type="text")
     */
    private $Description;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $Lieu;

    /**
     * @ORM\Column(type="date")
     */
    private $Date;

    /**
     * @ORM\ManyToOne(targetEntity=User::class, inversedBy="events")
     * @ORM\JoinColumn(nullable=false)
     */
    private $Auteur;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNom(): ?string
    {
        return $this->Nom;
    }

    public function setNom(string $Nom): self
    {
        $this->Nom = $Nom;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->Description;
    }

    public function setDescription(string $Description): self
    {
        $this->Description = $Description;

        return $this;
    }

    public function getLieu(): ?string
    {
        return $this->Lieu;
    }

    public function setLieu(string $Lieu): self
    {
        $this->Lieu = $Lieu;

        return $this;
    }

    public function getDate(): ?\DateTimeInterface
    {
        return $this->Date;
    }

    public function setDate(\DateTimeInterface $Date): self
    {
        $this->Date = $Date;

        return $this;
    }

    public function getAuteur(): ?User
    {
        return $this->Auteur;
    }

    public function setAuteur(?User $Auteur): self
    {
        $this->Auteur = $Auteur;

        return $this;
    }

 
}

templates/events/create_events.html.twig
{% extends "_templates.html.twig" %}

{% block title %}
    Profil de {{ app.user.pseudo }}
{% endblock %}

{% block content %}
    <div class="section">
        <h1 class="title">Créer un évenement</h1>

        <div class="columns">
            <div class="column">
                <h3 class="subtitle">Evenements</h3>

                {{ form_start(events_form) }}

                {{ form_row(events_form.nom, {
                    label: 'Nom:'}) }}

                {{ form_row(events_form.description, {
                    label: 'Description:'}) }}

                {{ form_row(events_form.lieu, {
                    label: 'Lieu:'}) }}

                {{ form_row(events_form.date, {
                    label: 'Date:'}) }}

                <button type="submit" class="button is-info is-fullwidth">
                    Create
                </button>

                {{ form_end(events_form) }}
            </div>
        </div>
    </div>
{% endblock %}

templates/events/created_events.html.twig
{% extends "_templates.html.twig" %}

{% block title %}
    Created Events
{% endblock %}



{% block content %}
    <div class="section">
        <h1 class="title"> Created Events : {{ created_events|length }} </h1>

        <div class="columns is-multiline">
            {% for events in created_events %}
            <div class="column is-one-third">
                <div class="box">
                    <article class="media">
                        <div class="media-left">
                            <figure class="image is-128x128">
                                <img src="https://loremflickr.com/256/256/" alt="Image">
                            </figure>
                        </div>
                        <div class="media-content">
                            <div class="content">
                                <p>
                                    <a href="{{ path('events_page', {id: events.id})}}" class="has-text-primary">
                                        <strong>{{ events.nom }}</strong>
                                    </a>
                                    <br>
                                    {{ events.description|slice(0, 25) }}
                                </p>
                            </div>
                        </div>
                    </article>
                </div>
            </div>
            {% endfor %}
        </div>
    </div>
{% endblock %}

templates/events/events_page.html.twig
{% extends "_templates.html.twig" %}

{% block title %}
    Events: {{ events.nom }}
{% endblock %}

{% block content %}
    <section class="section">

        {% include 'includes/flash.html.twig' %}
        
        <div class="columns">
            <div class="column is-two-fifth">
                <figure class="image is-1by1">
                    <img src="https://loremflickr.com/1024/1024/album,music/all?lock={{ events.id }}">
                </figure>
            </div>

            <div class="column">
                <h2 class="subtitle">
                    Events:
                    <a href="{{ path('created_events', {id: events.id}) }}">
                        {{ events.nom }}
                    </a>
                </h2>

                <p class="content">
                    {{ events.description }}
                </p>

                <hr>

                {% if modifdelete_form is not null %}
                    <hr>
                    {{ form_start(modifdelete_form) }}
                    {{ form_row(modifdelete_form.nom, {
                        label: 'Nom:'}) }}
    
                    {{ form_row(modifdelete_form.description, {
                        label: 'Description:'}) }}
    
                    {{ form_row(modifdelete_form.lieu, {
                        label: 'Lieu:'}) }}
    
                    {{ form_row(modifdelete_form.date, {
                        label: 'Date:'}) }}
    

                    <button type="submit" class="button is-primary is-fullwidth">
                        Modifier
                    </button>

                    {{ form_end(modifdelete_form) }}
                {% else %}
                    <div class="section">
                        <article class="message is-info">
                            <div class="message-body">
                                Connectez-vous pour pouvoir modifier cet event!
                            </div>
                            <div class="buttons is-centered">
                                <a href="{{ path('app_login') }}" class="button is-info">
                                    Connexion
                                </a>
                                <a href="{{ path('app_register') }}" class="button is-info">
                                    Inscription
                                </a>
                            </div>
                        </article>
                    </div>
                {% endif %}
            </div>
        </div>
                    {% if is_granted("MODIF_DELETE") %}
                        <div class="media-right">
                            <a class="tag is-danger" href="{{ path('modif_delete', {id: modifdelete.id}) }}">
                                Supprimer
                                <span class="delete"></span>
                            </a>
                        </div>
                    {% endif %}
                </article>
            </div>
    </section>
{% endblock %}